# Tópicos

1. Tensores

2. Iniciando Tensores
    * Direto de Dados
    * De um ```np.array```
    * De outro Tensor
    * De valores aleatórios ou constantes

3. Operações com Tensores
    * Indexing and Slicing
    * Concatenating
    * Operações aritméticas
    * Tensores de elemento único
    * Operações diretas

4. Compatibilidade com Numpy
    * ```np.array``` para Tensor

# Tensores

Tensores são estruturas de dados semelhantes a vetores e matrizes. No PyTorch, os tensores são usadas para codificar entradas e saídas de um modelo e parâmetros.

Tensores são semelhantes ao ```np.array```, com a diferenla de que podem ser acelerados por GPU

In [75]:
import torch
import numpy as np

# Iniciando Tensores

Tensores podem ser iniciados de diversas formas

Exemplos:

#### Direto de Dados

In [76]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

#### De um ```np.array```

In [77]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

#### De outro Tensor

In [78]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0660, 0.5413],
        [0.0829, 0.8158]]) 



#### De valores aleatórios ou constantes

In [79]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8445, 0.6752, 0.4450],
        [0.1381, 0.1997, 0.8533]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Operações com Tensores

Há mais de 1200 operações, incluindo aritmética, álgebra linear, manipulação de matrizes (transposição, index, slicing), amostragem e outras. [Mais operações](https://pytorch.org/docs/stable/torch.html)

Cada operação pode ser executada em GPU e acelerada com CUDA, MPS, MTIA ou XPU.

Por padrão, tensores são criados na CPU. Porém, recursos de aceleração podem ser alocados, como abaixo:

In [80]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x_data = x_data.to("cuda")

print(x_data.device)
print(torch.cuda.get_device_name(0))
print(torch.cuda.current_device())
print(torch.cuda.device_count())

cuda:0
NVIDIA GeForce RTX 4060 Ti
0
1


#### Indexing and Slicing

In [81]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Concatenating

In [82]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### Operações aritméticas

Multiplicação matricial entre tensores

In [83]:
print(f"Tensor original: \n {tensor} \n")

tensorT = tensor.T
print(f"Tensor transposto: \n {tensorT} \n")

y1 = tensor @ tensor #Tensor transposto
print(f"Multiplicação matricial: \n {y1} \n")

y2 = tensor.matmul(tensorT)
print(f"Multiplicação matricial com matmul: \n {y2} \n")

z1 = tensor * tensor #Elemento por elemento
print(f"Multiplicação elemento por elemento: \n {z1} \n")

z2 = tensor.mul(tensor)
print(f"Multiplicação elemento por elemento com mul: \n {z2} \n")

Tensor original: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

Tensor transposto: 
 tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Multiplicação matricial: 
 tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]]) 

Multiplicação matricial com matmul: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

Multiplicação elemento por elemento: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

Multiplicação elemento por elemento com mul: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



#### Tensores de elemento único

Tensores de elemento de único podem ser convertidos para valores numéricos nativos

In [84]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


#### Operações Diretas

Operações podem ser atribuidas diretamente a um tensor com um ```_```

In [85]:
print(f"Tensor original: \n {tensor} \n")
tensor.add_(5)
print(f"Tensor após adição direta: \n {tensor} \n")

Tensor original: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

Tensor após adição direta: 
 tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



# Compatibilidade com Numpy

Tensores e ```np.array``` podem compartilhar o mesmo espaço de memória

In [86]:
t = torch.ones(5)
print(f"t: \n {t}")
n = t.numpy()
print(f"n: \n {n}")

t: 
 tensor([1., 1., 1., 1., 1.])
n: 
 [1. 1. 1. 1. 1.]


Mudanças no tensor causam mudanças no ```np.array```

In [87]:
t.add_(1)
print(f"t: \n {t}")
print(f"n: \n {n}")

t: 
 tensor([2., 2., 2., 2., 2.])
n: 
 [2. 2. 2. 2. 2.]


#### ```np.array```to Tensor

In [88]:
n = np.ones(5)
t = torch.from_numpy(n)

In [89]:
np.add(n, 1, out=n)
print(f"t: \n {t}")
print(f"n: \n {n}")

t: 
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: 
 [2. 2. 2. 2. 2.]
